config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects do
    resources :bookings, only: [:create]
    resources :likes, only: [:create]
  end

  resources :bookings, only: [:index, :show, :destroy] do
    member do
      patch :accept
    end
    member do
      patch :reject
    end
  end

  resources :likes, only: [:destroy]

  resources :charities

  get "profile", to: "pages#profile"

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-style">
    <div style="margin-right: 30px;">
      <h2 class="about"><b>About Us</b></h2>
        <p>FAQ</p>
        <p>Donate Here</p>
        <p>Our Team</p>
        <p>Contact Us</p>
        <p>Terms and Conditions</p>
    </div>
    <div style="margin-right: 30px;">
      <h2 class="resources"><b>Resources</b></h2>
        <p>Blog</p>
        <p>Medium</p>
        <p>Press</p>
    </div>
    <div class="">
      <h2 class="Corperate"><b>Corporate</b></h2>
      <p>Events</p>
    </div>
  </div>
  <div class="footer-links-right">
    <div>
      <h2 class="follow"><b>Follow Us</b></h2>
      <div class="footer-links">
        <a class="icons" href="#"><i class="fab fa-instagram"></i></a>
        <a class="icons" href="#"><i class="fab fa-facebook"></i></a>
        <a class="icons" href="#"><i class="fab fa-twitter"></i></a>
        <a class="icons" href="#"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>
    <div>
      <a class="icons" href=""><i class="far fa-copyright"></i> Code for Change 2020</a>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%=  'transparent' if controller_name = 'bookings' && action_name = 'show' %>">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag 'cfc2.jpg' %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% unless current_user && current_user.coder %>
        <%= link_to "Create a project", new_project_path, class: "nav-link" %>
      <% end %>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Projects", projects_path, class: "nav-link" %>
        </li>
        <% if current_user.charity %>
          <li class="nav-item">
            <%= link_to "Charity profile", charity_path(current_user.charity), class: "nav-link" %>
          </li>
          <li>

            <!-- <a class="btn btn-flat" href="/projects/new">Charity? Create a Project</a> -->
          </li>
        <% else %>
        <li class="nav-item">
            <%= link_to "My Profile", "/profile", class: "nav-link" %>
          </li>
          <% end %>
        <li class="nav-item dropdown">
          <%= image_tag "https://i.ya-webdesign.com/images/avatar-icon-png-6.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <p class="dropdown-item" style="margin: 0px"> <%= current_user.email %></p>
            <%#= link_to "Project Dashboard", profile_path(anchor: 'projects'), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
      <li class="nav-item">
         <li class="nav-item">
          <%= link_to "Sign Up as a Charity", new_user_registration_path(coder: false), class: "nav-link" %>
        </li>
          <%= link_to "Sign Up As Coder",  new_user_registration_path(coder: true), class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>