config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects do
    resources :bookings, only: [:create]
    resources :likes, only: [:create]
  end

  resources :bookings, only: [:index, :show, :destroy] do
    member do
      patch :accept
    end
    member do
      patch :reject
    end
  end

  resources :likes, only: [:destroy]

  resources :charities

  get "profile", to: "pages#profile"

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :charity
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_many :likes, dependent: :destroy
  has_one_attached :photo
  has_one_attached :file

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_project, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      sql_query = "name ILIKE :query \
      OR project_description ILIKE :query \
      OR location ILIKE :query \
      OR category @@ :query"
      @projects = Project.where(sql_query, query: "%#{params[:query]}%")
    else
      @projects = Project.all
    end
  end

  def show
    @markers = [{
      lat: @project.latitude,
      lng: @project.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { project: @project }),
      image_url: @project.photo.service_url
    }]
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.charity = current_user.charity
    @project.deadline = Date.parse(params.dig(:project, :deadline)).strftime('%d/%m/%Y')
    if @project.save!
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @project.update(project_params)
		redirect_to project_path(@project)
  end

  def destroy
    charity = @project.charity
    @project.destroy
		redirect_to charity_path(charity)
  end

  private

  def project_params
    params.require(:project).permit(:name, :category, :project_description, :location, :trello_token, :photo, :deadline)
  end

  def find_project
    @project = Project.find(params[:id])
  end
end

app/views/projects/_info_window.html.erb
<h3>
  <%= project.name %>
</h3>

<p>
  <%= project.category %>
</p>

app/views/projects/index.html.erb
<div class="banner-index" >
  <div class="banner-container">
    <h1 class="index-header" style="font-family: 'Oswald', sans-serif;">PROJECTS</h1>
    <div class="container-form">
      <%= form_tag projects_path, class: "search-form", method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a project"
        %>
        <button type="submit" class="btn">
          <i class="fa fa-search grow"></i>
        </button>
      <% end %>
      </div>
  </div>
</div>
<div class="container search">
  <div class="container-index">
    <div class="cards">
      <% @projects.each do |project| %>
        <div class="card-product">
          <div class="overlay-fade">
            <% if project.photo.attached? %>
              <%= cl_image_tag project.photo.key, class: 'first-charity-photo' %>
                <div class="index-text" style="">
                  <%#= link_to 'Learn More', project_path(project) %>
                 </div>
            <% end %>
          </div>
          <div style="display: flex; flex-direction: column; height: 100%; width: 100%;">
            <div class="card-product-infos project-card">
              <div class="title-heart">

                <h2><%= project.charity.name %></h2>
                <% if current_user&.charity.nil? %>
                  <% if project.likes.where(user_id: current_user&.id).length == 1 %>
                    <%= link_to like_path(project.likes.where(user_id: current_user&.id)[0]), method: :delete, class: "save-heart-index" do %>
                      <i class="fas fa-heart"></i>
                    <% end %>
                  <% else %>
                    <%= link_to  project_likes_path(project), method: :post, class: "save-heart-index", remote: true do %>
                      <i class="far fa-heart"></i>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
              <p>Category: <%=project.category %></p>
              <p>Location: <%= project.location %></p>
              <p>Project description: <%= project.project_description.truncate(120) %> </p>
            </div>
            <%= link_to "Learn More", project_path(project), class: "btn btn-flat-index" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="index-back">
    <%= link_to "Back to Home", root_path, class: "btn btn-flat" %>
  </div>
</div>
<script>
  document.addEventListener('turbolinks:load', () => {
    if (localStorage['scroll']) {
      window.scroll({ top: localStorage['scroll'] });
    }
    window.addEventListener('scroll', () => {
      localStorage['scroll'] = window.scrollY;
    });
  })
</script>

app/views/projects/new.html.erb
<div class="create-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80)">
  <h1 class="project"><b>CREATE A PROJECT NOW</b></h1>
</div>

<div class="container">
  <div class="project-form project-new">
     <%= simple_form_for [@charity, @project] do |f| %>
       <%= f.input :name, label: "Enter the name of your project" %>
       <%= f.input :category, :collection => %w[Front-end Back-end Full-stack], label: 'Enter the type of project you want completed' %>
       <%= f.input :deadline, as: :date, html5: true, order: [:day, :month, :year], label: 'Submit the date you would like your project to be completed' %>
       <%= f.input :point_of_contact, label: 'Enter an e-mail for the individual who will be the point of contact for the duration of the project'%>
       <%= f.input :location, label: 'Enter the address of your charity', input_html: {class:"location_input"}%>
       <%= f.input :project_description, as: :text, label: 'Give a short description of your project and the functions and/or design features you want included'%>
       <%= f.input :file, as: :file, label: 'Attach your detailed project brief' %>
       <%= f.input :photo, label: 'Attach your a photo for your charity'%>
       <%= f.input :trello_token %>
       <%= link_to 'Authorize Trello', "https://trello.com/1/authorize?expiration=never&name=Code For Change&scope=read&response_type=token&key=#{ENV['TRELLO_API_KEY']}", target: '_blank', class:"btn btn-info" %>

       <%= f.submit 'Create a project', class: "btn btn-dark"  %>

     <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="banner-show" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @project.photo.key %>);">
   <%= link_to projects_path do %>
      <i class="fas fa-arrow-left back-arrow"></i>
    <% end %>
  <h1 class="charity-name"><%=@project.name%></h1>
  <div class="container">
    <div class="row justify-content-center">
      <div class="card text-center show-card">
        <div class="card-header tab-header d-flex align-items-center justify-content-start">
          <span class="tab active show-tab" role="tab" aria-controls="project-description" aria-selected="true">Project Information</span>
          <span class="tab show-tab" role="tab" aria-controls="charity-description" aria-selected="false">Charity Information</span>
        </div>
         <div class="card-body">
          <div class="tab-content mt-3">
            <div class="tab-pane active" id="project-description" role="tabpanel">
              <p class="card-text"><%= @project.project_description %></p>
              <div class="project-card-overview">
                <p class="card-inform">Deadline:  <%= @project.deadline %></p>
                <p class="card-inform">Note: This is a <%= @project.category %> project</p>
                <% if current_user.charity.nil? %>
                  <%= link_to project_bookings_path(@project, page: 'show'), method: :post do %>
                    <button type="button" class="btn-request" >I'm In!</button>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="tab-pane d-none" id="charity-desc" role="tabpanel" aria-labelledby="chrarity-description-tab">
            <p class="card-text"><%= @project.charity_description %></p>
            <p class="charity-link">For more information, please visit: <%= @project.website %></p>
          </div>
        </div>
        <% if current_user.charity.nil? %>
          <% if @project.likes.where(user_id: current_user.id).length == 1 %>
            <%= link_to like_path(@project.likes.where(user_id: current_user.id)[0], project_id: @project.id), method: :delete, class: 'save-heart' do %>
              <i class="fas fa-heart"></i>
            <% end %>
          <% else %>
            <%= link_to project_likes_path(@project, page: 'show'), method: :post, class: 'save-heart' do %>
              <i class="far fa-heart"></i>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>


  <h1 class="important-info">Further Information</h1>

<div class="container">
  <div class="row">
    <div class="col-md-5">
      <div id="map"
      style="width: 100%;
      height: 600px;"
      data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
    <div class="col-md-7">
      <div class= "card card-important-info">
          <h2 class="important-title">Please note:</h2>
          <ul class="important-body">
            <li>You are only permitted to work on one project at a time </li>
            <li>More information will be given once you have been accepted to the project.</li>
            <li>The time it will take to complete each project will depend on the project complexity, please be mindful and realistic about the requirements. </li>
            <li>In most cases, you will be collaborating on this project with other individuals using the platform.</li>
            <li>Code For Change does not take gender or age into account. This will provide you with valuable experience in working within diverse teams, which is a reality of the contemporary workplace.</li>
            <li>Each charity has a representative that will act as your point of contact throughout the project. This will be the person who you are able to reach out to for questions specific to the needs of the project.</li>
            <li>Once you complete your project, you can add the product to your portfolio. Your goal is to leave behind a well documented solution that can be easily maintained by the organization.</li>
            <li>Both the charity, your collaborators and the Code For Change team is counting on you to complete the project. Should you leave the project before completion you will be banned from joining any future projects.</li>
          </ul>
      </div>
    </div>
  </div>
</div>