config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects do
    resources :bookings, only: [:create]
    resources :likes, only: [:create]
  end

  resources :bookings, only: [:index, :show, :destroy] do
    member do
      patch :accept
    end
    member do
      patch :reject
    end
  end

  resources :likes, only: [:destroy]

  resources :charities

  get "profile", to: "pages#profile"

end

app/models/charity.rb
class Charity < ApplicationRecord
  belongs_to :user
  has_many :projects, dependent: :destroy
  has_one_attached :photo
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  before_action :find_charity, only: [:edit, :update, :destroy, :show]

  def new
    @charity = Charity.new
  end

  def create
    user = current_user
    @charity = Charity.new(charity_params)
    @charity.user_id = user.id
    if @charity.save
      redirect_to charity_path(@charity)
    else
      redirect_to  new_charity_path
    end
  end

  def show
  end

  def edit
  end

  def update
    @charity.update(charity_params)
    redirect_to project_path(@charity)
  end

  def destroy
    @charity.destroy
    redirect_to charities_path
  end

  private

  def charity_params
    params.require(:charity).permit(:name, :description, :location, :photo, :deadline)
  end

  def find_charity
    @charity = Charity.find(params[:id])
  end
end

app/views/charities/new.html.erb
<h2 class="h2-signup">Register Your Charity</h2>
  <div class ="session-grid3">
    <div class="session-grid-form">
      <div class="form-inputs">
        <%= simple_form_for @charity do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :photo, as: :file, label: 'Charity Banner' %>
          <%= f.input :location, input_html: {class:"location_input"} %>
          <%= f.input :email %>
          <%= f.input :website %>
          <%= f.input :charity_registration_number %>
          <%= f.button :submit, "Register Your Charity With Us", class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/charities/show.html.erb
<div class="banner-charity" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @charity.photo.key %>);">
<div class="charity-header">
  <div class="your-charity-details">
    <h1 class ="welcome" style="font-family: 'Oswald', sans-serif;">Welcome <%= @charity.name %></h1>
    <br>
    <h4 class ="how" style="font-family: 'Oswald', sans-serif;">How is <%= @charity.location %> today?</h4>


  </div>
  <%= link_to "Create a Project", new_project_path, class: "btn btn-flat charity-show-button" %>
</div>
</div>




<%# @charity.projects.each do |project| %>
  <% if @charity.projects.all? { |p| p.bookings.where(status: 'Pending').empty? } %>
    <h1 class="Waiting"> Waiting for applications! </h1>
  <% else %>
    <div class="your-charity-applications design-table">
      <h2 style="font-family: 'Oswald', sans-serif;">Applications</h2>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">PROJECT</th>
            <th scope="col">APPLICANT</th>
            <th scope="col">LINKEDIN PROFILE</th>
            <th scope="col">GITHUB PROFILE</th>
            <th scope="col">BIO</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @charity.projects.each do |project| %>
            <% project.bookings.where(status: 'Pending').each do |booking| %>
            <tr class="test-d">
              <td><%= project.name %></td>
              <td><%= booking.user.name %></td>
              <td><%= link_to "LinkedIn", booking.user.linkedin_url, target: '_blank',class: "btn btn-dark btn-block"  %></td>
              <td><%= link_to "Github", booking.user.github_url, target: '_blank',class: "btn btn-dark btn-block"  %></td>
              <td><%= booking.user.bio %></td>
              <td><%= link_to 'Accept', accept_booking_path(booking), method: :patch, class: "btn btn-outline-success" %></td>
              <td><%= link_to 'Reject', reject_booking_path(booking), method: :patch, class: "btn btn-outline-danger" %></td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
<%# end %>




<div class="your-charity-projects">
  <h2 style="font-family: 'Oswald', sans-serif; color: black;">Our Projects</h2>
  <% if @charity.projects.empty? %>
      <h1 class="projects-are-empty"> You currently don't have any projects registered 🙁 <br> <%= link_to "Create a Project", new_project_path, class: "btn btn-flat charity-show-button btn-register-now" %></h1>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">PROJECT</th>
          <th scope="col">CATEGORY</th>
          <th scope="col">DUE DATE</th>
           <th scope="col">ACTION</th>
        </tr>
      </thead>
      <tbody>
        <% @charity.projects.each do |project| %>
          <tr>
<!--             <%# if project.bookings.present? %>
              <td><%#= link_to project.name || @charity.name, booking_path(project.bookings.first.id),class: "btn btn-dark btn-block " %></td>
            <%# else %>
              <td><%#= project.name %></td>
            <%# end %> -->
            <td class="profile-project-name"><%= link_to project.name, project_path(project) %></td>
            <td><%= project.category %></td>
            <td><%= project.deadline %></td>
            <td><%= link_to 'Delete Project', project_path(project), method: :delete, class: "btn btn-dark btn-block" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>